### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by etweisberg** [etweisberg/peptoid_db_website#30]
- [x] Make images for residue structures

- [x] Determine what to do for 13AC1-6-A, 08AC1-6-C, 06AA1-9-A

- [x] Obtain images for peptoids

- [x] Figure out file naming scheme

**Comment by etweisberg** [comment]
Remaining peptoids to generate images for

- 13AC1-6-A
- 08AC1-6-C
- 06AA1-9-A

**Comment by jameseastwood** [comment]
These three are actually missing published coordinates, so I can't generate
images for them. We will need to flag them to discuss with Kent whether
they ought to be excluded from the data bank.
